### ISSUE TITLE
Did you fork Skypher's montezuma ?

### ISSUE THREAD

**Issue by vindarel** [sharplispers/montezuma#10]
Hi, 

I first saw this repo https://github.com/skypher/montezuma/ and then yours. It looks like you forked him and commited 6 bug fixes since. Is that what happened, any plan to merge the two libs ?

Regards.

**Comment by xach** [comment]
This is the canonical location of montezuma. There are no plans to merge with @skypher's version, which is unmaintained.

**Comment by vindarel** [comment]
Allright, thanks !
